### ISSUE TITLE
Java is difficult to recognize

### ISSUE THREAD

**Issue by geekscloud** [antelle/intellij-xcode-dark-theme#10]
Thank you for making this plugin. I don’t speak English. Please understand. I am a JAVA developer and I am trying to use this theme. I compared the color of Xcode, and I found that the color is missing in the JAVA code. Some colors make the code difficult to distinguish. It would be great if it could be the same as the new Xcode 11 version

**Comment by antelle** [comment]
Hi! I’m using it to develop Java as well, could you please paste a screenshot of what you see, and explain what is seen as an issue?

**Comment by zhoushiwang99** [comment]
![image](https://user-images.githubusercontent.com/43675156/98903124-eb664b00-24f1-11eb-92ee-a730631ec4cd.png)
White background is hard to discern with CTRL +F12

**Comment by zhoushiwang99** [comment]
Is there a way to solve it？

**Comment by antelle** [comment]
Hm, it’s not supposed to be white, which version is that?

**Comment by zhoushiwang99** [comment]
![image](https://user-images.githubusercontent.com/43675156/98904878-641ad680-24f5-11eb-9945-8bd1837a75f4.png)
![image](https://user-images.githubusercontent.com/43675156/98904901-71d05c00-24f5-11eb-9245-612e2d421264.png)

**Comment by zhoushiwang99** [comment]
![image](https://user-images.githubusercontent.com/43675156/98904943-86145900-24f5-11eb-8302-d623401cb054.png)
I disabled it and it  returned  normal

**Comment by antelle** [comment]
It doesn’t behave like this for me, do you maybe have any plugins installed?

**Comment by zhoushiwang99** [comment]
![image](https://user-images.githubusercontent.com/43675156/98906467-0b990880-24f8-11eb-94ac-6228ab147fbc.png)
![image](https://user-images.githubusercontent.com/43675156/98906516-24a1b980-24f8-11eb-951a-c501a2b77d3f.png)
Oh,Right!I forgot I installed another theme plugin, so I disabled it and it works!

**Comment by zhoushiwang99** [comment]
Thanks!

**Comment by antelle** [comment]
I guess that’s also a theme but it adds something to another theme? I can take a look why it happens.

**Comment by antelle** [comment]
Just checked, this happens only if the "Material Theme UI" plugin is enabled, so actually when that theme is in use, there are more things that are broken with this setup. I don't think we'll be able to fix it, since it's also a theme that customizes UI in its own way. I would say, choose any of them, they're mutually exclusive.
