### ISSUE TITLE
How to change background color?

### ISSUE THREAD

**Issue by adrianofreires** [antelle/intellij-xcode-dark-theme#11]
I'm sorry if I'm asking this in the wrong place, but where do I change the background color that is highlighted in the image?

![Captura de tela 2020-11-13 085242](https://user-images.githubusercontent.com/38692077/99070000-30d85600-258e-11eb-8bea-f048cf7b3154.png)

**Comment by antelle** [comment]
Hi! I don’t know, this is something that you should ask jetbrains, a theme can only customize this color to one value.
