### ISSUE TITLE
git file diff theme Incompletes coverage

### ISSUE THREAD

**Issue by FikaCode** [antelle/intellij-xcode-dark-theme#13]
#### on git file diff  window, theme Incompletes coverage.

![2021-02-25 172544](https://user-images.githubusercontent.com/42266215/109132784-2df52000-778f-11eb-9635-728974c33cef.png)

**Comment by antelle** [comment]
Hi! Strange, it's not like this for me, is it the same for other languages too?

<img width="1324" alt="Screen Shot 2021-02-25 at 17 30 20" src="https://user-images.githubusercontent.com/633557/109184345-30f01080-778f-11eb-9cc1-9e54c65d17a7.png">

**Comment by antelle** [comment]
Do you maybe have any other appearance extensions installed?

**Comment by antelle** [comment]
Looks very similar to #14, actually

**Comment by FikaCode** [comment]
Hi, I'm sorry, I'm very busy these two days,  so can't reply in time . actually，theme Incompletes coverage because of another theme，uninstall， work perfect. Thank you.
![2021-02-28 092559](https://user-images.githubusercontent.com/42266215/109405068-7edf6100-79a7-11eb-92ef-92b1415771f5.png)

**Comment by antelle** [comment]
Interesting, I just tried installing Cyan Light Theme, however it doesn't change anything if it's not enabled. But good that it works now!  
Or, was it "BetterIntelliJ"? I can't find this plugin in the plugin repository, not sure what it is.
