### ISSUE TITLE
Bad visibility due to coloring

### ISSUE THREAD

**Issue by waldzwoelf** [antelle/intellij-xcode-dark-theme#14]
### This appears to happen only on some pop-up menus like "Generate" in editor or Project View:

![editor3](https://user-images.githubusercontent.com/68006737/109305162-9ef31100-783d-11eb-9978-bdc96ca4d1ff.jpg)

![editor0](https://user-images.githubusercontent.com/68006737/109303730-7cf88f00-783b-11eb-902b-6326d2c9676f.jpg)

### As well as in some settings views:

![editor1](https://user-images.githubusercontent.com/68006737/109303731-7d912580-783b-11eb-838c-b5e2ab6e5206.jpg)

![editor2](https://user-images.githubusercontent.com/68006737/109305274-c518b100-783d-11eb-997e-f455815d0bf3.jpg)

I tried tweaking the color schemes but no luck.
Any ideas on how to fix this ?
Still love your theme!

> Windows 10 & macOS 
> Webstorm 2020.3.2 (and previous versions)

**Comment by antelle** [comment]
Hi! The interface doesn't look native, do you have any other extensions installed? This may cause it.

**Comment by waldzwoelf** [comment]
I thought I had disabled all the other plugins to test the behavior, but apparently I forgot to disable (or restart IDE after disabling) **Material Theme UI**. That Plugin caused some additional theming. 
Disabling it fixed my issue, which seems so obvious now. 
Thanks for your fast answer and sorry for wasting your time 😅

**Comment by antelle** [comment]
I'll check if it's possible to fix this with "Material Theme UI" because overall it seems to be looking what it should be, apart from some places.

**Comment by antelle** [comment]
Fixed some of colors, uploaded an update to the repository. I can't figure out how to update the tab color on Settings / Plugins though.

**Comment by waldzwoelf** [comment]
Nice! Still fixed some color issues. Loving it even more now!
