### ISSUE TITLE
Can we have the same background color for all the IDE?

### ISSUE THREAD

**Issue by gilbertohnrq** [antelle/intellij-xcode-dark-theme#15]
I really like this theme, but i feel like I'd like it more if we had the same background color for all the IDE, like in the explorer etc.

**Comment by antelle** [comment]
Hi! Could you please explain what you mean? It's somewhat similar.

**Comment by gilbertohnrq** [comment]
Hi,
Idk if it's possible to use the same blue-ish background color in the whole IDE instead of just behind the code, but I'd really like that. ^^

![Screenshot_1](https://user-images.githubusercontent.com/29513598/111881199-31468a80-898e-11eb-80e4-bf775d8cb3f8.png)

**Comment by antelle** [comment]
You can change the source control editor background in settings: Editor / Color Scheme / General / Text / Default Text / Background.

Apart from this, other colors are similar to each other, I don't think they should be exactly the same. You probably need another theme for this change, it should be easy to fork and change them.
