### ISSUE TITLE
Can we do Light variant too?

### ISSUE THREAD

**Issue by aasutossh** [antelle/intellij-xcode-dark-theme#16]
I would definitely use the light variant of this. Pretty cool.

**Comment by aasutossh** [comment]
https://plugins.jetbrains.com/plugin/15727-xcode-theme nevermind.

**Comment by aasutossh** [comment]
> https://plugins.jetbrains.com/plugin/15727-xcode-theme nevermind.

I don't feel it's light version.

**Comment by antelle** [comment]
The plugin you posted seems to provide a light version though.

**Comment by aasutossh** [comment]
Yes it does provide the light version, not that my opinion matters, I didn't like it. Going to close this issue. It's opinion based.

**Comment by antelle** [comment]
I don’t like that light version either.
For the light version I’m actually using IntelliJ’s macOS theme, it provides native buttons and looks quite good, apart from the color scheme (in my opinion). I’ll check if it’s possible to inherit from it.

**Comment by aasutossh** [comment]
I've never really found good light themes.

**Comment by antelle** [comment]
I just checked, it's unfortunately not possible to inherit the `macOS Light` theme which is heavily customized inside IntelliJ, and without this theme the "macOS" UI doesn't look very good. So I'm not sure.

**Comment by antelle** [comment]
Ideally it should be a light color scheme, not theme, but it's also not possible to choose how to switch custom color schemes in IntelliJ.
