### ISSUE TITLE
Rider Poor cshtml highlighting

### ISSUE THREAD

**Issue by TechnicallyMay** [antelle/intellij-xcode-dark-theme#17]
The highlighting for html within code doesn't work in cshtml files

![image](https://user-images.githubusercontent.com/40505704/123649808-492c7680-d7e7-11eb-9555-1385ba216484.png)

**Comment by antelle** [comment]
Hi! Is it highlighted in the default theme?

**Comment by TechnicallyMay** [comment]
Thanks for the quick response. It is indeed highlighted in the default theme. Here's an example in Darcula
![image](https://user-images.githubusercontent.com/40505704/123664326-792e4680-d7f4-11eb-9113-c3d2f063cfde.png)

And here's Rider Light
![image](https://user-images.githubusercontent.com/40505704/123664396-8b0fe980-d7f4-11eb-9980-193c3a10bf83.png)

**Comment by antelle** [comment]
I see, it probably includes some additional definitions compared to intellij. I'll look into it, thanks.

**Comment by antelle** [comment]
I need some help with it. Rider also doesn't highlight XML colors at all for me, while IDEA does:

![image](https://user-images.githubusercontent.com/633557/123863309-b811e880-d929-11eb-9f12-05b94aa2efc8.png)

No idea why it behaves like this, to be honest. I've checked a number of other themes and .cshtml is highlighted properly there.

**Comment by TechnicallyMay** [comment]
![image](https://user-images.githubusercontent.com/40505704/123874606-ad3d6080-d8f5-11eb-9614-af8a0d92c84a.png)
Xml formatting looks correct to me in Rider

**Comment by TechnicallyMay** [comment]
I was able to resolve this by disabling the `foreground` option here

![image](https://user-images.githubusercontent.com/40505704/123875354-c1ce2880-d8f6-11eb-8de0-ee2ba1b2d57d.png)

**Comment by antelle** [comment]
Thanks you! 👍  Uploaded a new version with this fix.

**Comment by TechnicallyMay** [comment]
Thanks! And I appreciate the theme, I use it exclusively :)
