### ISSUE TITLE
can't show the color of non-project file's tab

### ISSUE THREAD

**Issue by actforjason** [antelle/intellij-xcode-dark-theme#18]
As a non-project file , pyplot.py's tab hasn't color. But, under Darcula theme, which can be set with color.

![image](https://user-images.githubusercontent.com/57058325/124352049-9027cb00-dc30-11eb-9527-012fcd00b916.png)

![image](https://user-images.githubusercontent.com/57058325/124352187-80f54d00-dc31-11eb-8032-1dbb20415273.png)

**Comment by actforjason** [comment]
editing there works:
https://github.com/antelle/intellij-xcode-dark-theme/blob/5a20a02f979aea621640a14ebd80798c2ff829b8/resources/Xcode-Dark.theme.json#L124
```json
    "EditorTabs": {
      "background": "#3c3e3e",
      "borderColor": "#6a6a6a",
      "hoverBackground": "#727272",
      "inactiveColoredFileBackground": "#654f12"
    },
```

**Comment by antelle** [comment]
Changing just `inactiveColoredFileBackground` is actually sufficient.

**Comment by actforjason** [comment]
Yes, I add some helpful colors.
