### ISSUE TITLE
Selection Color of completion list conflict with Symbol Text colors

### ISSUE THREAD

**Issue by gayanper** [antelle/intellij-xcode-dark-theme#2]
![color-issue](https://user-images.githubusercontent.com/7471994/67698922-41447f80-f9d1-11e9-87bb-145b4c477e77.png)

**Comment by antelle** [comment]
Hi! What looks better to you?

<img width="574" alt="Screen Shot 2019-10-29 at 09 02 30" src="https://user-images.githubusercontent.com/633557/67741639-dcb60e80-fa2a-11e9-923d-647aaa853aaa.png">


<img width="580" alt="Screen Shot 2019-10-29 at 08 59 18" src="https://user-images.githubusercontent.com/633557/67741517-729d6980-fa2a-11e9-8272-969d4fc7f2a4.png">

**Comment by gayanper** [comment]
Both are fine with me. But like the screenshot 1 the most out of two.

**Comment by antelle** [comment]
me too, will make a build with it today.

**Comment by gayanper** [comment]
Great, thanks for the quick fix. Let me know once you publish.

**Comment by antelle** [comment]
Fixed in decd00f155f4bf0746093c6f6a6a7acf86e07841, uploaded to JetBrains, the moderation usually takes 1-2 days.

**Comment by antelle** [comment]
@gayanper it's published

**Comment by gayanper** [comment]
@antelle thanks for the quick fix
