### ISSUE TITLE
Does not works in Android Studio 2021.3.1

### ISSUE THREAD

**Issue by filosofisto** [antelle/intellij-xcode-dark-theme#20]
After install the plugin and restart the IDE, the theme does not appears in the theme dropdown.

![image](https://user-images.githubusercontent.com/1119247/128128591-27ac2c2a-080c-4ed5-aba9-5eb4ec0af70a.png)

![image](https://user-images.githubusercontent.com/1119247/128128735-c7743bf1-9b87-4f9c-895a-694ff354314c.png)

**Comment by antelle** [comment]
see #19

**Comment by nikunjparadva** [comment]
## Here is the Solution
https://stackoverflow.com/a/68599712/5773037
