### ISSUE TITLE
could I change the left Project Tree's backgroud color?I can't find a place to edit it,very thanks

### ISSUE THREAD

**Issue by 1772523056** [antelle/intellij-xcode-dark-theme#21]
<img width="405" alt="截屏2021-08-09 上午1 51 50" src="https://user-images.githubusercontent.com/59076130/128640997-d256efde-b0b9-4000-a7c0-64ff79072bc3.png">

**Comment by antelle** [comment]
Hi! I don't think there's a possibility to change it apart from building your own theme based on another theme.
