### ISSUE TITLE
change font size

### ISSUE THREAD

**Issue by mirjamuher** [antelle/intellij-xcode-dark-theme#22]
Not an issue, more a question. I love the theme, but the font size is too small for my shabby eyes. Is there a way to increase the size? I tried via preferences > Appearance & Behaviour > Appearance but that seems to only affect the IDE itself, not the font of the code. Thank you for helping me with that :)

**Comment by antelle** [comment]
Hi! I think what you're looking for is in Preferences / Editor / Font.

**Comment by mirjamuher** [comment]
That was it - thank you so much! :)
