### ISSUE TITLE
Keyword color

### ISSUE THREAD

**Issue by DreamSaddle** [antelle/intellij-xcode-dark-theme#24]
Hello, why is my keyword lighter in color?

Version: 1.2.4
IED: WebStorm

![image](https://user-images.githubusercontent.com/31559386/145965406-d08ea7ef-92df-41c3-84da-21d39b437ccc.png)

**Comment by antelle** [comment]
Hi! Is is the same in other languages?
I see that other keywords are "washed out" a bit too. Can't help further.

**Comment by DreamSaddle** [comment]
@antelle 
Yes, such as python.

![image](https://user-images.githubusercontent.com/31559386/146107623-99547bb3-807f-4024-9e63-94209e6c4ee5.png)

**Comment by antelle** [comment]
Check if you have other plugins enabled, this doesn't look normal. Perhaps some plugin is messing with UI colors.
