### ISSUE TITLE
Color Issue on Diagram Window 

### ISSUE THREAD

**Issue by honood** [antelle/intellij-xcode-dark-theme#3]
I got the same results when trying the follow case in IntelliJ IDEA Ultimate and RubyMine:

1. Position the I-beam in the context of any Ruby class; 
2. Double click SHIFT key and select "Diagrams";
3. Select "Show Diagram Popup...";
4. Select "Ruby Class Diagram";
5. You would see just like the following popup window: 
<img width="921" alt="Screen Shot 2019-12-29 at 21 13 33" src="https://user-images.githubusercontent.com/665595/71557453-6a40c980-2a81-11ea-8578-3c61e644db98.png">

> macOS 10.15.2 (19C57)
> IntelliJ IDEA Ultimate 2019.3.1
> RubyMine 2019.3.1
> XCode-Dark Theme 1.0.5

**B.T.W.:** Darcula theme and color scheme works fine.

**Comment by antelle** [comment]
Hi! Looks like it looks a bit different in my IDEA, but I've never done anything with Ruby. Is there any project where I can make this diagram? Or can you please save this diagram to a file and attach here?

**Comment by antelle** [comment]
Looks like I figured it out myself, it shows built-in classes grayed out, if I configure the SDK, it behaves in the same way.

**Comment by antelle** [comment]
Fixed it, the new release should be approved in 1..2 days:

<img width="418" alt="diagram" src="https://user-images.githubusercontent.com/633557/71558765-ebcf3200-2a56-11ea-8cb9-fe96315d7320.png">
