### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by MX-Qulin** [antelle/intellij-xcode-dark-theme#4]
Hi,there.
       This Xcode-dark-theme really attracts me, and i can't wait to use it. However, I finally noticed that it can only run on intellij... It's very disappointing... **So, is it possible to run it on Pycharm? If not, would you please make it possible to run on Pycharm?**
      Second, dark themes are great, but i suppose that there also need to be a light theme. What's your opinion? **Hope you to develope an "Xcode-light-theme"**
                                                                    👍 Best regards  @antelle

**Comment by antelle** [comment]
Hi! The JetBrains' plugin repository website says it should be available for all IDE's, including PyCharm.

<img width="823" alt="Screen Shot 2020-07-03 at 16 46 12" src="https://user-images.githubusercontent.com/633557/86479590-bd574a00-bd4c-11ea-9239-778d97499e58.png">

I'm not interested in a light theme so I won't make it.
