### ISSUE TITLE
Font color not changing after applying theme

### ISSUE THREAD

**Issue by 97alexlo** [antelle/intellij-xcode-dark-theme#5]
Hi. I'm new to pycharm to I might be doing something wrong. The font colors are not changing but the font and other things are after applying the theme. for example, "if" is brown while it should be pink. Thanks
![Capture](https://user-images.githubusercontent.com/50306893/89753508-710ad280-da8d-11ea-82de-885325b4c719.PNG)

**Comment by antelle** [comment]
Hi! This is the Color Scheme setting. It should be possible to change it in Settings / Editor / Color Scheme / Scheme.

**Comment by sudogene** [comment]
Hey I don't think the theme is working as intended on PyCharm, I've set the Scheme in Color Scheme editor settings and it does not change to the expected colors.

**Comment by antelle** [comment]
That's strange, there shouldn't be a difference between different IDE's. Which version of PyCharm do you have?

**Comment by sudogene** [comment]
I'm on the latest version:
Version: 2020.2
Build: 202.6397.98

Font colors on PyCharm
![1](https://user-images.githubusercontent.com/49007969/90644178-04e75600-e267-11ea-93ab-493fc74b5053.PNG)

Font colors on IntelliJ (also Version 2020.2)
![2](https://user-images.githubusercontent.com/49007969/90644368-3bbd6c00-e267-11ea-81a6-3e4d593536da.PNG)

**Comment by antelle** [comment]
Right, if I install Python plugin, it becomes like this as well, so Python needs color definitions for it.

**Comment by antelle** [comment]
Fixed it, the release is coming in a couple of days

**Comment by antelle** [comment]
The update seems to be already published.

**Comment by sudogene** [comment]
Works now thanks a lot!
