### ISSUE TITLE
Single color everywhere

### ISSUE THREAD

**Issue by napsterv** [antelle/intellij-xcode-dark-theme#7]
![image](https://user-images.githubusercontent.com/8555852/95476732-2c27ed00-09a5-11eb-81ac-40d945ccfc1e.png)

The theme seems to render everything in pink.

I've tried other themes to cross-check and they do apply different colors.

Is there a way to mix up the colors a bit? It's a tad bit difficult to focus.

**Comment by antelle** [comment]
Well that's what it's supposed to be. For example, JavaScript is also less colorized in Xcode. Not sure how to make them different without losing this similarity, to be honest.  
If you like just the UI theme without editor colors, it's possible to change them to a different setup.

**Comment by antelle** [comment]
Example of Swift in Xcode, which is the most properly colored language there, it's also similar in terms of palette used:  
<img width="1072" alt="Screen Shot 2020-10-08 at 21 24 33" src="https://user-images.githubusercontent.com/633557/95504203-bcb5fb80-09ac-11eb-88d5-4d9d0a2c6f06.png">

**Comment by napsterv** [comment]
I see, I see. Looks like, we're restricted by the color palette, there's nothing much we can do. 🙄
