### ISSUE TITLE
Theme colors after install are different from what they are supposed to be

### ISSUE THREAD

**Issue by 1rusl1** [antelle/intellij-xcode-dark-theme#9]
Hi
I found your theme on marketplace and really liked the colors, but when I and apply It install It, I get completely different colos comparing to screenshots
![image](https://user-images.githubusercontent.com/25434871/97324408-dac39d00-1882-11eb-98e2-119601f05932.png)

This is my appearance and color scheme settings: 
![image](https://user-images.githubusercontent.com/25434871/97324539-fdee4c80-1882-11eb-8256-56164e8991db.png)
![image](https://user-images.githubusercontent.com/25434871/97324608-1494a380-1883-11eb-9cf4-2798329ae09a.png)

**Comment by antelle** [comment]
I see that the colors match, but they're somewhat washed out. Not sure why it happens, I assume it's not because of a theme.

**Comment by antelle** [comment]
Or, have you changed the colors with something? What exactly do you see as an issue, UI colors or text editor colors?

**Comment by 1rusl1** [comment]
@antelle Thanks for the fast response! UI colors are great, but the editor colors looks like some color blind mode are turned on, or something like that. I tried to remove this mark on Appearance menu and restart AppCode, but result is the same:
![image](https://user-images.githubusercontent.com/25434871/97368049-314ccd80-18bb-11eb-96f1-f59df3375e99.png)
![image](https://user-images.githubusercontent.com/25434871/97368087-41fd4380-18bb-11eb-925a-4040e5bbad81.png)

**Comment by antelle** [comment]
Not sure what this is, but it seems to be coming not from a theme, we don’t have such colors. What if you use another color scheme and another theme?

**Comment by 1rusl1** [comment]
If I use another color scheme It works just fine. For example Hiberbee Dark:
![image](https://user-images.githubusercontent.com/25434871/97395449-07fd6300-18f6-11eb-8ecc-f3160ac3b11a.png)

But I really liked your theme, and I would like to use It instead

**Comment by antelle** [comment]
That's also different from what it's supposed to be, compare:

![theme](https://user-images.githubusercontent.com/633557/97481712-7b828d00-1955-11eb-9b74-8696673789da.png)

But it doesn't look ugly because colors are very saturated and they look rather good with your transformation. I can't help here, sorry, looks like there's something changing colors in your IntelliJ or system-wide.
